### ISSUE TITLE
Dashboard of cityfirst.in

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/cityfirst_issues#1]
Right now the display is like this
![capture](https://cloud.githubusercontent.com/assets/5755132/7782310/d1a4b294-012d-11e5-9440-79b36d25a6cd.PNG)

It should be something like this -
1. Total 5 reports on the left hand side 1/4th area. Add 6th report of pending complaints which are unassigned.
2. The right hand side 3/4 should have a google map showing the resolved complaints dots in green and pending complaints in red dots.
3. The dashboard should have a dropdown list of nagarpalikas of the district. Something similar to
   ![capture](https://cloud.githubusercontent.com/assets/5755132/7782319/07d8c0d4-012f-11e5-94ce-bb589b477c90.PNG) 
   This way we can see nagarpalika wise overall picture in number as well as graphically.

**Comment by vikaswriteme** [comment]
Dear Sir,

Map view done as suggested thanks for this wonderful input
Regards

**Comment by drdhaval2785** [comment]
Why no proper CSS and hyperlinking to the figures?
![capture](https://cloud.githubusercontent.com/assets/5755132/7952114/49f44cfc-09ce-11e5-84b7-2734f76a2465.PNG)

**Comment by drdhaval2785** [comment]
Right now the main page google map display is fine. Proper dimention.
But when I select proper nagarpalika, the display should increase.
e.g. current display when I selected Borsad nagarpalika is 
![capture](https://cloud.githubusercontent.com/assets/5755132/7952999/c28788ca-09db-11e5-905b-b3a6a5bd9338.PNG)

Expected output should be 
![capture](https://cloud.githubusercontent.com/assets/5755132/7952973/914bd770-09db-11e5-8210-4de2280158f4.PNG)

**Comment by vikaswriteme** [comment]
Sir Done
