### ISSUE TITLE
complain.aspx - status

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/cityfirst_issues#11]
![capture](https://cloud.githubusercontent.com/assets/5755132/7782442/8861b008-0134-11e5-9dd5-c497e5982b1a.PNG)

These two symbols have no heading above them.
It is difficult to guess why they are there.
Write `Details` and `Status` above these two column as headers

**Comment by vikaswriteme** [comment]
Dear Sir,

symbol status labled

Regards
