### ISSUE TITLE
user.aspx - nagarpalikas not shown

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/cityfirst_issues#12]
When I select Anand District, only Anand nagarpalika is shown.
Incorporate other NPs too.
![capture](https://cloud.githubusercontent.com/assets/5755132/7782447/0ed2d86a-0135-11e5-9c59-6616291f188f.PNG)

**Comment by vikaswriteme** [comment]
Sir now all nagarpalikas are shown

Regards
