### ISSUE TITLE
dashboard.aspx - masters tab

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/cityfirst_issues#13]
Masters tab has the following details
1. District
2. Nagarpalika
3. Complaint Type
4. Complaint Subtype

Right now there is no possibility of adding a new nagarpalika in the masters.
It should have a Create, Edit and Delete facility to add / remove nagarpalikas.

Same with Create, Edit and Delete the complaint type and subtypes.

The system should be scalable.

**Comment by vikaswriteme** [comment]
Dear Sir,

Nagarpalika name can be added now
Regards
