### ISSUE TITLE
viewcomplain.aspx?id=535

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/cityfirst_issues#14]
I will note my observations on the complaint detail page.
http://cityfirst.in/viewcomplain.aspx?id=535 is the test page.
It looks like the following right now

![capture](https://cloud.githubusercontent.com/assets/5755132/7782465/0b3d85d6-0137-11e5-9f66-8be7023c3c24.PNG)

**Comment by drdhaval2785** [comment]
In my opinion, map view should not be an external link.
Use google map API to create a google map in our site itself.

**Comment by vikaswriteme** [comment]
Sir map view done

**Comment by drdhaval2785** [comment]
Changes uploaded on live server or offline code corrected?

**Comment by drdhaval2785** [comment]
Checked. Right now the map view shows whole of gujarat by default. Actualky
it should not show more than 1 square kilometer on screen because we are
primarily dealing with small areas of municipality.

**Comment by drdhaval2785** [comment]
To give a visual feel of what I ask for

Current display:
![capture](https://cloud.githubusercontent.com/assets/5755132/7877308/bcce28c8-05f6-11e5-80ac-96629f28ea45.PNG)

Expected display:
![capture](https://cloud.githubusercontent.com/assets/5755132/7877302/a4b24a30-05f6-11e5-9c47-e34e304b2ab6.PNG)

**Comment by vikaswriteme** [comment]
Sure Sir will be done

**Comment by vikaswriteme** [comment]
Sir now it is done as suggested by u
regards
