### ISSUE TITLE
App cache

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/cityfirst_issues#15]
Right now everytime I have to enter First name, Middle Name, Last name, Gender and Nagarpalika name manually.
I guess it is better if we fetch that data from cache.
If the user wants to change it he can very well change it, but writing this everytime is absolute waste of time.

**Comment by vikaswriteme** [comment]
Good idea sir will be done.

**Comment by vikaswriteme** [comment]
Dear Sir,

one query for taking name directly from cache in app it will take last entered name automatically but may i also give them option to change the name.

Regards

**Comment by drdhaval2785** [comment]
yes

**Comment by vikaswriteme** [comment]
Dear Sir,

App Cache is done i have updated the apk on google play store it will updated on ur phone by 4-5 hrs

Regards

**Comment by vikaswriteme** [comment]
sir done
