### ISSUE TITLE
cityfirst.in details in open domain

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/cityfirst_issues#16]
All the reports and complaint status / complaint details etc should be available on open domain (i.e. without username password). 

Only for assigning / resolving the complaints there should be a username / password required.
Opening the data to the whole world is the best disinfectant.

**Comment by vikaswriteme** [comment]
Sure sir will be done

**Comment by drdhaval2785** [comment]
Make sure you edit the trailing mail next time (when you reply via mail).
Otherwise unnecessary cluttering would happen

**Comment by vikaswriteme** [comment]
Dear sir,
Open domain task done
Regards
