### ISSUE TITLE
gujarati labels in App and site

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/cityfirst_issues#17]
Both app and site should have English / Gujarati options.
Labels in Gujarati in Gujarati interface of app
and 
English in English interface

**Comment by vikaswriteme** [comment]
sir gujarati label in site done
Regards

**Comment by drdhaval2785** [comment]
`English / Gujarati options`

We would like to cater to both the options. One click on some button which says English / Gujarati.
So that the user can utilize both the languages.
Right now it has been 100 % changed to Gujarati

**Comment by drdhaval2785** [comment]
For a visual feel
![capture](https://cloud.githubusercontent.com/assets/5755132/7953067/f12c85ee-09dc-11e5-89e8-5358dc0e716e.PNG)

In the abovementioned space
Put a tab 'ગુજરાતી' when the user is having English version.
Put a tab 'English' when the user is having Gujarati version.

This way the user would be able to navigate between English and Gujarati version of our website

**Comment by vikaswriteme** [comment]
sir option done

**Comment by drdhaval2785** [comment]
Option is done.
But the dropdown has only Gujarati label and English figures.
Irrespective of the language selected
Actually it should be Gujarati label : Gujarati numbers for Gujarati UI
And English label : English numbers for English UI.

![capture](https://cloud.githubusercontent.com/assets/5755132/11868142/d3f478ac-a4db-11e5-9ea4-da6c2e588312.png)

**Comment by vikaswriteme** [comment]
Sir its done. Kindly check
