### ISSUE TITLE
SMS to complainant

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/cityfirst_issues#19]
Right now there is only one SMS (when the complaint is redressed)

Actually, there should be three SMSs.
1. Your Complaint related to ProblemName in X nagarpalika Y ward has been received. Your complaint ID is 123456.
2. Your complaint 123456 has been assigned to person X of Y nagarpalika and his contact number is -----------.
3. Your complaint 123456 has been resolved. If you are not satisfied with the response, you can reopen the complaint by clicking ABCD (link to reopen the complaint). If you are satisfied, please share the link on social media by clicking PQRS (link to share on social media)

**Comment by drdhaval2785** [comment]
Right now the text of msg is 'Your cityfirst complaint has been resolved'.
If I have 3 pending complaints - how would I know which complaint has been resolved.
It needs to be given number 'Your cityfirst complaint number XYZ has been resolved'.

**Comment by vikaswriteme** [comment]
Sir done
