### ISSUE TITLE
counter issue

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/cityfirst_issues#2]
Right now the dashboard shows total 1472 complaints.
![capture](https://cloud.githubusercontent.com/assets/5755132/7782325/938a0dcc-012f-11e5-96dc-8a0a3683d058.PNG)

When I click on that 1472 complaints, I see the following detail i.e. 472 complaints (which is the correct number)
![capture](https://cloud.githubusercontent.com/assets/5755132/7782328/bebfd0da-012f-11e5-966f-367fd81f8e41.PNG)

I guess there is some issue in the counter in dashboard

**Comment by drdhaval2785** [comment]
In my opinion, it echoes one additional '1' before the actual figure.

**Comment by vikaswriteme** [comment]
Dear Sir,

Counter issue resolved

regards
