### ISSUE TITLE
map display deprecated

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/cityfirst_issues#23]
Because we are showing the map inside the complaint,
The link to google map view is not needed.

![capture](https://cloud.githubusercontent.com/assets/5755132/7953053/b200ea86-09dc-11e5-8452-d81ebd5c0618.PNG)

**Comment by drdhaval2785** [comment]
It seems that the map itself has gone away.
Bring it back.

**Comment by vikaswriteme** [comment]
Sir its done. Kindly check

**Comment by drdhaval2785** [comment]
Done.

Note to @vikaswriteme -
It is a good idea to document the corrections you did e.g. folder / file / code name etc so that it would be easier for you to locate the corrections made let's say 4 months later.
