### ISSUE TITLE
Gujarati lablel corrections

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/cityfirst_issues#24]
http://www.cityfirst.in/dashboard.aspx

કમ્પ્લેનની યાદી - ફરિયાદોની યાદી
મેપ - નકશો
પ્રોબ્લેમ - ફરિયાદનો પ્રકાર
view problem - ફરિયાદ જુઓ
resolved - નિકાલ થયેલ
unknown status - બાકી ફરિયાદ
All - તમામ
assigned - અસાઇન કરેલ
not assigned - અસાઇન ન કરેલ

**Comment by drdhaval2785** [comment]
http://www.cityfirst.in/dashboard.aspx

ટોટલ કમ્પ્લેન - કુલ ફરિયાદો
ટોટલ રીસોલ્વ કમ્પ્લેન - નિકાલ થયેલ ફરિયાદો
ટોટલ રીસોલ્વ ન થઇ સકતી કમ્પ્લેન - નિકાલ ન થઈ શકતી ફરિયાદો
૭ દિવસ જૂની કમ્પ્લેન - ૭ દિવસથી જૂની ફરિયાદો
બાકી કમ્પ્લેન - બાકી ફરિયાદો
ટોટલ જીપીએસ રીપોર્ટ - કુલ જીપીએસ રીપોર્ટ

**Comment by drdhaval2785** [comment]
Masters tab

નગરપાલીકા - નગરપાલિકા
કમ્પ્લેન ટાઇપ - ફરિયાદનો પ્રકાર
કમ્પ્લેન સબટાઇપ - ફરિયાદનો પેટાપ્રકાર

**Comment by drdhaval2785** [comment]
http://www.cityfirst.in/complain.aspx

![capture](https://cloud.githubusercontent.com/assets/5755132/7953182/25c865fa-09df-11e5-956a-807d1e6f3322.PNG)
તમામ
અસાઇન થયેલ
અસાઇન ન થયેલ

![capture](https://cloud.githubusercontent.com/assets/5755132/7953185/371cdac0-09df-11e5-81dd-5853f557d425.PNG)
ફરિયાદ જુઓ
નિકાલ થયેલ ફરિયાદો

![capture](https://cloud.githubusercontent.com/assets/5755132/7953189/5de87b64-09df-11e5-8c46-bf87c2ccef00.PNG)
પ્રતિ પેજ
આંકડા ગુજરાતીમાં

![capture](https://cloud.githubusercontent.com/assets/5755132/7953200/7ee4c818-09df-11e5-903a-1580d3ddc8d4.PNG)
પ્રોબ્લેમ - ફરિયાદનો પ્રકાર
બાકી ફરિયાદો

**Comment by vikaswriteme** [comment]
Sir sorry

**Comment by vikaswriteme** [comment]
Dear Sir,

It is done
