### ISSUE TITLE
hovering in dashboard

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/cityfirst_issues#3]
When I hover mouse over the figure in dashboard 
![capture](https://cloud.githubusercontent.com/assets/5755132/7782342/7fb382aa-0130-11e5-991f-7752d1b956f1.PNG)
There should be a menu which shows Nagarpalika wise status.
It should go off when I move my mouse away from the number.
You will need some jquery / javascript / AJAX to do that.

**Comment by vikaswriteme** [comment]
Sir done
