### ISSUE TITLE
complain.aspx not showing all nagarpalikas

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/cityfirst_issues#4]
http://cityfirst.in/complain.aspx

When I choose District - Anand,
![capture](https://cloud.githubusercontent.com/assets/5755132/7782357/21ec6cd0-0131-11e5-89c0-15c92a3e6097.PNG)

Only Anand nagarpalika is shown.
The nagarpalika section should show all 11 nagarpalikas

**Comment by vikaswriteme** [comment]
Dear Sir,

now all nagarpalikas showing  resolved

Regards
