### ISSUE TITLE
complain.aspx search function not working

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/cityfirst_issues#5]
The search functionality is not working at all.
I chose Anand - Anand - Dhaval
![capture](https://cloud.githubusercontent.com/assets/5755132/7782359/75b8f19e-0131-11e5-881a-0d0f66614110.PNG)

Nothing happenned.

**Comment by vikaswriteme** [comment]
Dear sir,
complain search function is now working

Regards,
