### ISSUE TITLE
complain.aspx - when the user doesn't know the ward number

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/cityfirst_issues#9]
Most of the time the user doesn't know the ward number.
In such case, the display is like this.

![capture](https://cloud.githubusercontent.com/assets/5755132/7782431/ff86bc56-0133-11e5-953e-abddc401f521.PNG)

What I would advise is

```
Remove the space and - after the nagarpalika name if the ward number is not given
```

e.g.
`Anand` is better than `Anand -`

**Comment by drdhaval2785** [comment]
Same with the Problem section.
If the user has not provided the subtype of problem,
remove the space and -
e.g. in the above picture
`Garbage` is better than `Garbage -`

**Comment by vikaswriteme** [comment]
Sir It is resolved
